name: yid-tts
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.7.1
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - sentencepiece
  - cmake
  - xformers
  - pip
  - pip:
    - unsloth
    - transformers
    - datasets
    - soundfile
